require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admins::MessagesController do

  # This should return the minimal set of attributes required to create a valid
  # Admins::Message. As you add validations to Admins::Message, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { subject: "RSPEC TEST SUBJECT",
                             message: "RSPEC TEST MESSAGE" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admins::MessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admins_messages as @admins_messages" do
      message = Admins::Message.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admins_messages).should eq([message])
    end
  end

  describe "GET show" do
    it "assigns the requested admins_message as @admins_message" do
      message = Admins::Message.create! valid_attributes
      get :show, {:id => message.to_param}, valid_session
      assigns(:admins_message).should eq(message)
    end
  end

  describe "GET new" do
    it "assigns a new admins_message as @admins_message" do
      get :new, {}, valid_session
      assigns(:admins_message).should be_a_new(Admins::Message)
    end
  end

  describe "GET edit" do
    it "assigns the requested admins_message as @admins_message" do
      message = Admins::Message.create! valid_attributes
      get :edit, {:id => message.to_param}, valid_session
      assigns(:admins_message).should eq(message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admins::Message" do
        expect {
          post :create, {:admins_message => valid_attributes}, valid_session
        }.to change(Admins::Message, :count).by(1)
      end

      it "assigns a newly created admins_message as @admins_message" do
        post :create, {:admins_message => valid_attributes}, valid_session
        assigns(:admins_message).should be_a(Admins::Message)
        assigns(:admins_message).should be_persisted
      end

      it "redirects to the created admins_message" do
        post :create, {:admins_message => valid_attributes}, valid_session
        response.should redirect_to(Admins::Message.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admins_message as @admins_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::Message.any_instance.stub(:save).and_return(false)
        post :create, {:admins_message => {  }}, valid_session
        assigns(:admins_message).should be_a_new(Admins::Message)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::Message.any_instance.stub(:save).and_return(false)
        post :create, {:admins_message => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admins_message" do
        message = Admins::Message.create! valid_attributes
        # Assuming there are no other admins_messages in the database, this
        # specifies that the Admins::Message created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admins::Message.any_instance.should_receive(:update).with({ "subject" => "RSPEC TEST SUBJECT", "message" => "RSPEC TEST MESSAGE" })
        put :update, {:id => message.to_param, :admins_message => { "subject" => "RSPEC TEST SUBJECT", "message" => "RSPEC TEST MESSAGE" }}, valid_session
      end

      it "assigns the requested admins_message as @admins_message" do
        message = Admins::Message.create! valid_attributes
        put :update, {:id => message.to_param, :admins_message => valid_attributes}, valid_session
        assigns(:admins_message).should eq(message)
      end

      it "redirects to the admins_message" do
        message = Admins::Message.create! valid_attributes
        put :update, {:id => message.to_param, :admins_message => valid_attributes}, valid_session
        response.should redirect_to(message)
      end
    end

    describe "with invalid params" do
      it "assigns the admins_message as @admins_message" do
        message = Admins::Message.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::Message.any_instance.stub(:save).and_return(false)
        put :update, {:id => message.to_param, :admins_message => {  }}, valid_session
        assigns(:admins_message).should eq(message)
      end

      it "re-renders the 'edit' template" do
        message = Admins::Message.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admins::Message.any_instance.stub(:save).and_return(false)
        put :update, {:id => message.to_param, :admins_message => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admins_message" do
      message = Admins::Message.create! valid_attributes
      expect {
        delete :destroy, {:id => message.to_param}, valid_session
      }.to change(Admins::Message, :count).by(-1)
    end

    it "redirects to the admins_messages list" do
      message = Admins::Message.create! valid_attributes
      delete :destroy, {:id => message.to_param}, valid_session
      response.should redirect_to(admins_messages_url)
    end
  end

end
